### ISSUE TITLE
Highlander 732B Unusable?

### ISSUE THREAD

**Issue by IlluminousReality** [CptMoore/MechEngineer#101]
Good day,

Absolutely loving everything about this mod - I cannot even fathom the supreme amount of work, passion and effort that has gone into it. Thank you!

That said, I have an issue. I just received the Highlander 732B as a mission reward and am being told it is "unusable" due to "One or more components on this mech are installed in an invalid location."

As to why I think MechEngineer has anything to do with it, let me explain:

When I first started trying to set up MechEngineer, I ran into the strangest error: It would load, but ALL mechs at that time stated that "One or more components on this mech are installed in an invalid location." A Thunderbolt might look fine and have its engine, gyro, armor et al as components, whereas a Griffon wouldn't have any of the "Required Internal Components" this mod adds.

After pulling my hair out for a while I figured out that the fault lay with one of the very few other mods I'd hand-selected to work with MechEngineer. It didn't touch any of the same data, BUT it renamed the Heat Sinks, which "breaks" MechEngineer's setup. 

I removed the conflicting files from the other mod and MechEngineer set itself up perfectly and I've been playing 20 hours deeper with no further issues.

None of the other mods I use even begin to touch actual mech layouts at all, so there's no other possible conflicts with another mod touching the Highlander. 

Any thoughts on how to correct this? I've tried to dig around in the file structure and the .cs files but I can't see anything that would directly affect the Highlander but leave every other mech completely usable with no errors.
![highlandererror](https://user-images.githubusercontent.com/41887998/43379699-4f98d1c6-9393-11e8-9899-eeb318d2f6a1.jpg)

Thanks for your time and thanks again for the stupendous efforts!
~L

**Comment by IlluminousReality** [comment]
I am a dork. I fixed the error by removing the stock Fusion Core 215 (which I suspect is listed as a prohibited engine for the Highlander, being as it's very, very, very small for that chassis) and installing a new one. Sad to rip out a DHS engine and replace it with a SHS engine, but that's what conversion kits are for! 

How embarrassing. Feel free to ignore this post.

**Comment by CptMoore** [comment]
thanks for the report, I'm trying to make the mod as user friendly as possible while staying CBT faithful. so these reports help me even if they don't show an immediate issue.

However I do think you uncovered a actual issue within the mod, that came with one of the recent CC (Custom Components) updates

CC made it so that if you have more components used in a compartment than there is space, the mech becomes invalid. look at the legs, 2 slots in total possible, 4 in use.

the autofixer doesn't take that into account when fixing up mechs, I've created a new ticket in #102 for the specific issue
