### ISSUE TITLE
Customized "Light" Version

### ISSUE THREAD

**Issue by BlueStryker** [CptMoore/MechEngineer#124]
Hey CptMoore,

Again, I appreciate you allowing me to include your mod with mine, but I was wondering if I could request a customized "light" version. Basically, I only need the standard engines and gyros so I can make use of the damage/destruction scripting you've included. Until HBS moves the timeline forward I will not be including XL engines, or additional types of gyros (nor do I currently have need of FF, or ES). I also don't plan on allowing the engines/gyros to be removed or changed because I believe that, realistically, you shouldn't be able to do that kind of work on a Dropship (maybe on the Argo when you've unlocked all the repair upgrades, but not before). If you are willing to put together a version of your mod with the above specifications I'd be most appreciative, and will make a pull request for it. If you are unable or unwilling then I will simply do my best to alter you mod, but I am very much an amateur when it comes to scripting/coding. Either way, thank you for your time and consideration.

**Comment by LadyAlekto** [comment]
You just cut out everything you dont want and it wont appear in the game?

**Comment by CptMoore** [comment]
Unfortunatly I dont have time to do a light version. I cant even finish the standard version properly (ladys RT mod is the only proper ME implementation and ME standalone still is underdeveloped and not released on nexus)

In order to create a light version, one would need to understand shops, customcomponents categories and modtek. I really am searching for someone who can take on the task to finish develop and then maintain the basic and exotic versions. That person might also do a light version once that one shows up.
