### ISSUE TITLE
improve tooltip, item label and description texts

### ISSUE THREAD

**Issue by CptMoore** [CptMoore/MechEngineer#55]
I'm not fond of the way the items are called and how they display information

- gyro is fine for a name and icon, but its 0 tonnage
- XL Engine implies that the thats the whole engine, but we have so many parts to it now.. left, right, center and the actual core. need better naming for those.
- all those engine parts except for the core also are empty shells that satisfy requirements, but they don't have any meaning beyond that. no gameplay information displayed on them. the descriptions are nice but still 0 tonnage etc..

### split tonnage used between items
* gyro
* fusion core
* shielding

since shielding can reduce by half.. core is like 25% and shielding 75% for std?

requires an abstraction of the tooltip patch

### move tonnage information to shielding component

we don't know how much tonnage to calculate until that component is in the mech, so would make sense right?

requires rewrite and restructuring of engineCoreRef

### find a better name for "Engine" and "RT" "LT"

- XL Engine RT
- XL Engine LT
- XL Engine
- Fusion Core

Fusion core is ok
RT and LT have to be used to fit space wise or word wrapping happens.
So replace "Engine" with "Shielding"?

XL Shielding, kinda long and not entirely accurate. Lore wise other components are part of an engine too.
XL Components is way to long.
XL Materials, is long but sounds cool, but could also refer to Endo-Steel or FF though
XL Parts, same issue as Materials
XL Assembly, same issue as Materials
XL Case, unfortunately CASE is already reserved
XL Confinement, kinda long
XL Reactor ?!

Maybe I should just rename Fusion Core to "Engine Core" and be done with it,

**Comment by CptMoore** [comment]
@Aliencreature thoughts?

**Comment by Aliencreature** [comment]
One idea is to have:
Fusion Core
XL Engine RT
XL Engine CT
XL Engine LT

So they are uniform. One alternative might be XL Casing, but I don't particularly like it. In my opinion the best choice is to deviate as little as possible from the lore names, and make sure the description briefly mentions the difference between the parts.

The Fusion Core is where the magic happens, and where a tiny sun is formed that produces immense heat. But it is not an engine, it is merely a source of heat. The engine is the part that handles the conversion of that heat to useful work. This is also how it is in real life reactors, where the core and the engine/turbine systems are considered separate.

I would actually love it if Fusion Core was left as Fusion Core, because it keeps things open if anyone ever decides to add a Fission Core as a cheap, dirty alternative for when money is running dry.

The part that I am really struggling with is how much of an engine is the core and how much is the engine. It has been a while since I took math, but I've been at it for a few minutes and I can't seem to find a solution.

**Comment by CptMoore** [comment]
> XL Engine CT
> Fusion Core was left as Fusion Core

so it shall be.

> engine is the core and how much is the engine

so important for everything, weight, cost, properties.  we could continue to cheat by having everything in the fusion core.
only cost is left that can't be just part of only the core, but there I could just make the installation cost dynamically calculated.

the current cost formula for a standard engine is 5'000 * chassis max tons * rating / 75. an xl engine just replaces the 5'000 with 20'000.

how much of that cost is:
- installation
- materials (shielding, etc..?)
- fuel

and how does it each scale to rating and chassis tonnage?
going to read some of the rule books to get some inspiration

**Comment by Aliencreature** [comment]
Since I can not actually figure out how much of an engine is the core and how much the shielding, I decided to work at it backwards. I imported the engine table into LibreOffice and set up additional columns: one that takes the formula for the tonnage of the core based on rating, and one that subtracts it from the tonnage for each engine type to produce the shielding tonnage. That is to make sure that no nonsensical values are produced. As there are to my knowledge no engines below a rating of 60, I have used that as the floor.

**What I Found**

First of all, there are some limitations to what is possible.

1) Fusion cores have to accept tonnage values below 0.5 in order to not produce a nonsensical 0 tonnage XXL60 engine.
2) Because of ^, a linear function for core tonnage will always have to produce low values even at high ratings. This makes the mass of the core almost completely dependent on the shielding.

The first, and simplest solution, is to use a linear function to calculate the core tonnage based on rating. 

=MROUND(0.005*A12, 0.25)

After some playing around I found that the above plays well with all ratings.

I am working on other formulas that put more emphasis on the core tonnage at higher ratings, but this might be the way to go. It also makes sense, since in a modern nuclear reactor most of the mass is in shielding, cooling, etc. and not on the core itself.

**Comment by Aliencreature** [comment]
**OPTION 2**

I used an exponential fit function to reverse-engineer the formula that is used on the engine tables to correlate engine rating to tonnage, and then I sprinkled a few additions on-top.

Fusion Core Tonnage =MROUND(1.00922794448231^A12/5, 0.25)

The fusion core takes up ~ 20% of the STD engine, but that varies with engine size due to the rounding to the nearest 0.25. It plays nicely with all engine ratings and types EXCEPT:

XXL 70
XXL 75

Which produce a shield rating of 0. This, too, is an unfortunate side-effect of the rounding function, but they are fringe cases and I doubt they will be relevant (or even included if we follow MWO's example of having no engines under 100 except for the 60). If, however, that is a problem, an alternative formula is:

=MROUND(1.00922794448231^A12/5, 0.5)-0.25

This works for all engine ratings and types but is less elegant and produces odd-looking core tonnages.

**Comment by CptMoore** [comment]
based on how much stuff we have to do, I might scrap the idea of making engine components more immersive by distributing properties. right now, except for the space usage and cost, every property should be part of the core.

Costs just have to be calculated on the go. To properly calculate costs, we need to know:
(EngineTypeModifer x Engine Rating x Unit Tonnage) ÷ 75

On shop buy time, we don't know any of the information at the same time. (we might know rating or engine type but not both are even unit tonnage)

On installation time, theoretically it should be possible to have all 3 values, but practically we dont:
- engine rating is known already
- the unit tonnage is not given to the installation order (requires an easy but ugly patch)
- engine type is another component. this is a bigger issue, since we have race conditions in combination with cancelling an order.

The best one could do right now is to derive 2 formula:
1. fusion core installation cost (Engine Rating x Unit Tonnage)
2. shielding installation cost (Engine Type x Unit Tonnage)

for 2. I need to split EngineCoreRef from EngineType, probably introducing EngineRef -> ( EngineCoreRef, EngineTypeRef ). thats kinda a big change.

**Comment by CptMoore** [comment]
the cost issue can be solved with #66 thats alot of work though

**Comment by CptMoore** [comment]
closing this, not worth an extra issue
