### ISSUE TITLE
Rare Engines

### ISSUE THREAD

**Issue by Aliencreature** [CptMoore/MechEngineer#63]
@CptMoore I've seen you mention +++ versions of engines a few times, and I thought it'd be a good time to start discussing them even if they are only included in a future version. So far, engines are split in:

Fusion Core
Engine CT
_Engine LT_
_Engine RT_

As much as I would like to have +++ Fusion Cores, they make up the bulk of the current gear if we want to include all canon engine ratings. Thanks to the split between Engine CTs and Rating, the CTs can be used as the vessel for rare variations without creating a mess of jsons. The statuseffects system I used in previous versions to give XXL engines their extra heat can do pretty much everything.

STD Engines will be the vast majority of engines used in most playthroughs, and the most bland ones, so they would benefit the most from this. Potential bonuses that could be done with almost zero extra Harmony coding (aside from exposing JJ heat) are:

**Speed**
+20 / 40 / 60% Sprint

**JJs**
-20 / 40 / 60% JJ heat
+20 / 40 / 60% JJ distance

**Energy Weapons**
+10 / 20 / 30% Energy Damage
- 10 / 20 / 30% Energy Heat
+ 1 / 2 / 3 PPC Accuracy (explained as increasing the projectile's velocity)

**Ballistic Weapons**
+10 / 20 / 30% Gauss Damage

**Heat**
+ 10 / 15 / 20 Heat Dissipation/Turn
+ 20 / 40 / 60% Shutdown Threshold (NOT Overheat, that bonus is reserved for Compacts)

Thoughts?

**Comment by CptMoore** [comment]
## if we keep in mind later components we can reduce the list
> Speed

sprint distance should be reserved for leg mods (MASC). though until there are here, why not?

>JJs heat/distance

jj themselves could be rare items

> PPC / Gauss

I don't like buffing specific weapons as they just can have their own buffs directly on the weapon. i might be wrong though and maybe just hated having those targeting computers for each weapon type.

> Heat Dissipation

well obviously we can already buff this by inserting additional heat sinks ourselves, so meh as a bonus

## ideas I like
> Energy Weapons

now this makes a lot of sense, a bonus to all weapons that can't be applied several times.
could get rid of heat exchangers (which I never liked due to stacking issues), however I know that there is some special code that applies to weapons only for upgrades, and those engine parts are still heatsinks.

> Heat Shutdown

shutdown threshold is very nice idea

## new ideas
> JJ count

"MaxJumpjets" ++
( requires coding for mechlab )

> Morale

"MoraleBonusGain"
compact fusion is safer right due to less critical slots to hit
or if a fusion engine brakes down fewer times, morale is higher too
"reliable engine" status effect

**Comment by CptMoore** [comment]
another new idea, flamer damage boost! direct plasma exhaust vents

**Comment by CptMoore** [comment]
closing this, crazy ideas can be found in RT or added to RT
